var annotated_dup =
[
    [ "_PACKED", "struct__PACKED.html", "struct__PACKED" ],
    [ "AdcStatus", "structAdcStatus.html", null ],
    [ "Fsm", "structFsm.html", null ],
    [ "GpioAddress", "structGpioAddress.html", "structGpioAddress" ],
    [ "GpioInterrupt", "structGpioInterrupt.html", "structGpioInterrupt" ],
    [ "I2CPortData", "structI2CPortData.html", "structI2CPortData" ],
    [ "I2CSettings", "structI2CSettings.html", "structI2CSettings" ],
    [ "InterruptSettings", "structInterruptSettings.html", "structInterruptSettings" ],
    [ "LtcAfeRegisterData", "unionLtcAfeRegisterData.html", "unionLtcAfeRegisterData" ],
    [ "LtcAfeSettings", "structLtcAfeSettings.html", "structLtcAfeSettings" ],
    [ "LtcAfeStorage", "structLtcAfeStorage.html", "structLtcAfeStorage" ],
    [ "MPURegion", "structMPURegion.html", null ],
    [ "MPURegionSettings", "structMPURegionSettings.html", null ],
    [ "PedalCalibBlob", "structPedalCalibBlob.html", null ],
    [ "PedalCalibrationData", "structPedalCalibrationData.html", null ],
    [ "PedalCalibrationStorage", "structPedalCalibrationStorage.html", null ],
    [ "PersistHeader", "structPersistHeader.html", null ],
    [ "PersistStorage", "structPersistStorage.html", null ],
    [ "PwmInfo", "structPwmInfo.html", null ],
    [ "Queue", "structQueue.html", "structQueue" ],
    [ "Semaphore", "structSemaphore.html", "structSemaphore" ],
    [ "SPIPortData", "structSPIPortData.html", "structSPIPortData" ],
    [ "SpiSettings", "structSpiSettings.html", null ],
    [ "State", "structState.html", null ],
    [ "Task", "structTask.html", null ],
    [ "UartPortData", "structUartPortData.html", "structUartPortData" ],
    [ "UartSettings", "structUartSettings.html", "structUartSettings" ],
    [ "X86Interrupt", "structX86Interrupt.html", "structX86Interrupt" ]
];